version: 1

general:
  # Program will continue to run when enabled and sleep based on the monitor_sleep value.
  # True: enabled, False: disabled
  continuous_monitoring: False
  # Add the number of seconds to sleep between log checks. For continuous_monitoring only.
  # Limited to 4294967 seconds (49 days, 17:02:47).
  monitor_sleep: 2592000
  # True or False
  email_alerts: True
  # Sends email alerts with program crashes.
  # True: enabled, False: disabled
  alert_program_errors: True
  # Sets buffer days before certificate warnings start.
  buffer_days: 45
  # Sets timezome
  # Supports: CST, UTC, EST, MST, and PST
  time_zome: CST

site_urls:
  # Add additional URLs that need checked. All sites must support https.
  - google.com
  - ebay.com

email:
  smtp: smtp.yourdomain.com
  # True or False
  authentication_required: False
  username: SMTP_username
  # Leave blank if not required
  password: SMTP_password
  #True: Use TLS on port 587, False: Standard port 25
  use_tls: False
  from_email: alerts@monitoring.me
  to_email: youremail@monitoring.me

###############################################################################
############################Python Logging Setup###############################
###############################################################################
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s|%(levelname)s|%(message)s (Module:%(module)s, Function:%(funcName)s, Line:%(lineno)s)"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  certmonitor_log_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    # Default log paths are possible by typing DEFAULT in all caps. Manual paths can be entered as usual.
    # The default path option is only available when using the log_director function from ictoolkit.
    filename: DEFAULT
    # Sets max log file size to 10000 bytes (1 Megabyte)
    maxBytes: 2000000
    backupCount: 20
    encoding: utf8

loggers:
  __main__:
    level: INFO
    handlers: [console, certmonitor_log_file]
    propagate: no
  certmonitor.check.check:
    level: INFO
    handlers: [console, certmonitor_log_file]
    propagate: no
  ictoolkit:
    level: INFO
    handlers: [console, certmonitor_log_file]
    propagate: no
    
root:
  level: INFO
  handlers: [console]
